var x;
x = "Hello";
console.log(x);
var y;
console.log(y);
var isCorrect;
isCorrect = true;
console.log(isCorrect);
var countries = ['Russia', 'Germany', 'Portugal'];
var numbers = [1, 2, 3];
var t = [1, 'hi'];
console.log(countries, numbers, t);
var a;
a = 5;
a = 'hi';
a = true;
console.log(a);
var colors;
(function (colors) {
    colors[colors["red"] = 0] = "red";
    colors[colors["blue"] = 1] = "blue";
    colors[colors["yellow"] = 2] = "yellow";
    colors[colors["green"] = 3] = "green";
})(colors || (colors = {}));
;
var red = colors.red;
var blue = colors.blue;
var yellow = colors.yellow;
var green = colors.green;
console.log(colors);
